name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.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 }}
          user: MahboobAli1
          output_action: gist
